call_me_web_homepage:
    pattern:  /
    defaults: { _controller: CallMeWebBundle:Default:index }

register_page:
    path:     /register
    defaults: { _controller: CallMeWebBundle:Default:register }

process_register:
    path:     /process-register
    defaults: { _controller: CallMeWebBundle:Default:processRegister }