parameters:
#    call_me_web.example.class: CallMe\WebBundle\Example

services:
#    call_me_web.example:
#        class: %call_me_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
