parameters:

services:
    db:
        class: PDO
        arguments: ["mysql:dbname=%database_name%", %database_user%, %database_password%]

    user_factory:
        class: CallMe\WebBundle\Entity\User\UserFactory

    user_manager:
        class: CallMe\WebBundle\Entity\User\UserManager
        arguments: [@db, @user_factory]
